### ISSUE TITLE
Docker for Mac: ERROR: for kubelet  oci runtime error

### ISSUE THREAD

**Issue by leecalcote** [kubernetes/kubernetes-anywhere#136]
When bootstrapping a single-node local cluster per the instructions on [Docker for Mac](https://github.com/kubernetes/kubernetes-anywhere/blob/master/DOCKER_FOR_MAC.md) page, many kubernetes containers are created:

> Creating kube_proxy_1
> Creating kube_etcd_1
> Creating kube_kubelet_1
> Creating kube_apiserver_1
> Creating kube_scheduler_1
> Creating kube_controller-manager_1

 the following error is returned:

> ERROR: for kubelet  oci runtime error: rootfs_linux.go:89: jailing process inside rootfs caused "pivot_root invalid argument"
> Error response from daemon: Unable to remove filesystem for a2decf5c3499875d9ba0fe9d7428d8191c021d0d5291b87a003aef9cca13f66c: remove /var/lib/docker/containers/a2decf5c3499875d9ba0fe9d7428d8191c021d0d5291b87a003aef9cca13f66c/shm: device or resource busy

I'm using:
- OS X El Capitan 10.11.5
- Docker for Mac Version 1.12.0-rc2-beta16 (build: 9493)

**Comment by errordeveloper** [comment]
@leecalcote thanks very much for reporting it! I've just noticed this myself, it's definitely an issue with the latest Docker 1.12.0-rc2.

**Comment by errordeveloper** [comment]
I've reported this to Docker: https://github.com/docker/docker/issues/23767

**Comment by blackxored** [comment]
Any workarounds for this?

**Comment by errordeveloper** [comment]
Downgrading Docker for Mac and skipping updates should do.

**Comment by raeesiqbal** [comment]
Any update on this?

**Comment by errordeveloper** [comment]
Not yet, I'd hope next RC fixes the issue...

**Comment by raeesiqbal** [comment]
@errordeveloper Do you know of any other way of using Kubernetes on Docker for Mac?

**Comment by leecalcote** [comment]
@raeesiqbal yes, kube solo - https://github.com/TheNewNormal/kube-solo-osx

**Comment by raeesiqbal** [comment]
@leecalcote thanks :)

**Comment by squaremo** [comment]
This isn't just an issue when using Docker for Mac -- I ran into it using Docker 1.12-rc3 on Linux (Ubuntu 16.04, I installed Docker from their github releases page).

**Comment by zanhsieh** [comment]
same here with ubuntu 14.04 (docker 1.12.0)

**Comment by moondev** [comment]
any updates? would really love to run a local k8s cluster through docker and not any other tools

**Comment by zanhsieh** [comment]
@moondev: if you are looking for single node cluster, then minikube would fit your need. I look into this project mainly due to multi nodes & multi masters scenarios.

**Comment by moondev** [comment]
I've tried Minikube and it's great but i'm looking for a docker based
solution. Minikube uses virtualbox on windows which can't run when hyper-v
is enabled. (docker for windows runs in hyper-v). I'm close to getting a
cluster turnup on dind which sounds crazy but it just might work.

On Aug 11, 2016 6:02 PM, "zanhsieh" <notifications@github.com> wrote:

@moondev <https://github.com/moondev>: if you are looking for single node
cluster, then minikube would fit your need. I look into this project mainly
due to multi nodes & multi masters scenarios.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes-anywhere/issues/136#issuecomment-239329136>,
or mute the thread

**Comment by zanhsieh** [comment]
@moondev did you take a look at this? it seems closed; just wonder the proper --vm-driver switch would be.

https://github.com/kubernetes/minikube/issues/28

**Comment by moondev** [comment]
@zanhsieh it runs on windows but currently windows only supports the vbox driver

**Comment by gogeof** [comment]
not just MacOS, I face this problem with Centos 7.3.
