### ISSUE TITLE
Notify when phase2 succeeds or fails

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes-anywhere#140]
Right now terraform apply returns with a success message after phase1 and phase1b are complete. phase2 is run on the nodes and there is nothing that indicates whether that succeeded or failed. Users should be notified about phase2's success or failure.

cc @mikedanese

**Comment by colemickens** [comment]
I currently have the Azure `do deploy` outputting a `kubeconfig` file and then I manually use it and poll for `node` status and `componentstatuses` as well, similar to the validation logic in kube-up.sh now.

If we required the phase1's `do` script to create a `./tmp/kubeconfig` file, then there could be common logic that would use the `kubeconfig` file to do these checks.

I'd like this as well. Otherwise the user has to poll manually to know when the cluster is actually finished deploying.
