### ISSUE TITLE
Run weave node agent in a daemonset and use it to configure the pod network

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes-anywhere#151]
It should use kubelet cni plugin and be deployed as an addon in phase3.

**Comment by colemickens** [comment]
Is this being pushed instead of using native cloudprovider? Permanently? Temporarily? Is it because of Terraform not being able to cleanup routes/routetables/lbs?

I'm personally interested in having a native cloudprovider option. (Cleanup for Azure is a lot easier because each cluster gets a resource group that can be trivially deleted without needing to necessarily teach Terraform about cloudprovider-created resources.)

**Comment by mikedanese** [comment]
This will be a proof of concept that we can run the pod network as an addon. It proves that we can deploy kubernetes-anywhere in environments that don't by default support the routes that the pod network requires while meeting without sacrificing simplicity.

**Comment by aaronlevy** [comment]
Is this (theoretically) possible today, or is there more work that needs to happen? I'm not super familiar with the kubelet/CNI coordination points.

**Comment by mikedanese** [comment]
@aaronlevy I think this should work after https://github.com/kubernetes/kubernetes/pull/28178 is merged but I need to do some testing.
