### ISSUE TITLE
reconsider phase2 ansible dependency

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes-anywhere#160]
Ansible has good features:
- It's well known, often used and has a ton of documentation
- It's simple (at least the subset we are using) and declarative

Ansible has bad features:
- Requires python dependency on both server and target hosts
- It's super massive and is making deployment slow

Are there alternatives that have the good features without the massive set of dependencies?

**Comment by mikedanese** [comment]
Cloud-init, chef, puppet, salt all have similar issues

**Comment by errordeveloper** [comment]
The fact that Ansible is popular, which gives users a sense of familiarity and that is really major.

Another thing that users might think, is that they may be able to to leverage Ansible for some kind config management tasks on ***each machine*** in a live cluster, e.g. something about mounting disks or changing log rotation settings or tuning any sysctl flags, i.e. the thing people are used to with config management tools. So, they might want to be able to do such things and in some cases need to (or at least think that they need to) hook into something that Ansible k8s bootstrap is responsible for, e.g. restart kubelet as `/var/lib/kubelet` is being moved to a larger partition for whatever reason, and may be they've even decided to change the path and it became `/mnt/kubelet2`. The thing is that the way we are currently using Ansible with chroot implies that the code might not work out of the box when user tries to use in a different way (due to whatever assumptions authors have made), but user is very likely still going to spend time trying and might end-up hacking their own way to achieve what they wanted...

My point is that whatever we are doing, we need to make sure to give clear indication of how any ad-hoc automation should be done.

**Comment by mikedanese** [comment]
@errordeveloper @colemickens @madhusudancs  I intend to remove docker-images and ansible phase2's so we only have one phase2 (ignition). This is to satisfy the goal of having only one (portable) phase2 implementation.

**Comment by colemickens** [comment]
👍 I'll get Azure moved over either tonight or tomorrow.
