### ISSUE TITLE
Find best way of installing Docker

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#168]
There are too many ways Docker install can fail.

Today I noticed the apt repo was down (at least briefly), and `apt-get update` timed-out causing everything else to fail. Besides, we have seen https://github.com/docker/docker/issues/22599, which remains unresolved. In GCE we have `curl https://get.docker.com | sh` and in EC2 we install the official Debian package. I think that we should define some kind of standard way, and whatever we do probably should keep retrying until it succeeds.

**Comment by errordeveloper** [comment]
An alternative would be to use pre-baked images, which could work for some user, but makes certain things harder, and potentially leads to the route where root filesystem is considered immutable... For example, when user wishes to use their own images, they would have to be comfortable with our tooling, and understand what needs to be done when they wish to amend such images and if they should  trigger an update when publish updates, if they chose to keep on the immutable route; or what's the proper way for them to make any changes on running instances. I think that pre-baked images are a great optimisation, but it's something that needs to be very explicit, so I'd rather leave this to the user to implement they way they wish to, and instead rely on upstream distro channels to provide base images.

**Comment by mikedanese** [comment]
ref #137

**Comment by chuckbutler** [comment]
@errordeveloper we came into this problem ourselves delivering our Kubernetes/swarm bundles. We have just started adopting the pattern of delivering the Docker binary ourselves. The idea is to only support point in time releases, and always move the users forward just like Docker Inc. has been encouraging with their upstream repos. 

Its a little onerous to just take over all the packaging, but its like this: We're putting a binary blob on disk that does everything we need it to (thanks docker peeps for the dynamic bin!), and some dependency packages. Those are all served up by the distro backing the installation. Additionally some configuration files around the filesystem.

Seems straight forward enough unless the CGROUPS mounts get a drastic change, but its less likely to break or be unavailable if you're shipping that configuration+payload yourself, rather than relying on the extant sources. I'm pretty sure terraform has some mechanisms for delivering binary payloads during provisioning. [needs citation]
