### ISSUE TITLE
Use nsenter to launch kubelet

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#218]
RE: https://github.com/kubernetes/kube-deploy/pull/214

I don't know what that PR is about, but it seems like it would affect us too.

This is another case where `kube-deploy` and `kubernetes-anywhere` are drifting...

**Comment by cheld** [comment]
Container isolation causes a couple of problems when running kubelet in container. e.g. persistent storage is not working in OpenStack, because Cinder drivers are missing in hyperkube container. In most deployments kubelet is installed as binary on host. In this PR I kind-of do the same by merging host file system with container file system. BTW: works surprisingly well

**Comment by mikedanese** [comment]
We might want to just use the debian  pacakges

**Comment by cmluciano** [comment]
Can this issue be closed?

**Comment by cheld** [comment]
Thanks for closing
