### ISSUE TITLE
Generated state is very hard to keep track of

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes-anywhere#255]
When I first cloned this repo and created a cluster, it took me quite a while to realize where the script(s) actually store the generated state. It was scattered all over the place. I finally realized there's some stuff in:
- `./.config`
- `./.config.json`
- `./phase1/azure/.tmp/**`
- `./phase3/.tmp/**`

What if there was something like an `./output` directory that stores all the state and anytime we re-clone this repository, we just drop the `./output` there and everything works as expected.

This way, users would only need to backup the `./output` directory as opposed to keeping a copy of the entire repo.

Thoughts? @colemickens

**Comment by colemickens** [comment]
I had tried to do this in a previous PR but it was a bit fragile and it wound up being fairly complicated to get correct. WIP PR was here, but things got shuffled a lot since then: https://github.com/kubernetes/kubernetes-anywhere/pull/157

It's something I want to look at again, not sure how soon that will be though.

**Comment by cdornsife** [comment]
I have been storing state in the cluster. Then all you need is kubeconfig.json to restore it.

Here is a bash file that does the work. https://github.com/applariat/kubernetes-anywhere/blob/master/util/config-store.sh
