### ISSUE TITLE
Scale sets on azure

### ISSUE THREAD

**Issue by brunoriscado** [kubernetes/kubernetes-anywhere#265]
the old kubernetes binaries, used to provision azure with kube.sh created a cluster based on scale sets. Is this going to be a feature with kubernetes-anywhere?

Right now availability sets are provisioned, I reckon this is a bit of work on terraform's side of things. So I was wondering whether this is going to be a feature.

**Comment by colemickens** [comment]
No. For the time being, Kubernetes on Azure will be using AvailabilitySets directly due to some limitations in the VMSS APIs. We are working to bring the relevant APIs to VMSS, at which point in time we will transition back to VMSS.

This is discussed a bit here: https://github.com/colemickens/azure-kubernetes-status#notes

Let me know if that answers your question, or feel free to Close this Issue if it does.

**Comment by brunoriscado** [comment]
Thanks @colemickens it does answer my question.

**Comment by brunoriscado** [comment]
Thanks @colemickens it does answer my question.
