### ISSUE TITLE
Azure: support for multi-subscription clusters?

### ISSUE THREAD

**Issue by FilipVozar** [kubernetes/kubernetes-anywhere#307]
Hi, any plans to support Kubernetes clusters running on multiple Azure subscriptions (single cluster spanning multiple subscriptions)? There's [Azure BizSpark offer](https://azure.microsoft.com/en-us/pricing/member-offers/bizspark-startups/), which includes 5 subscriptions with free 150$/month, but there's no way to join those resources into one single subscription (many people have asked that).

I've been running a cluster in this mode for some time (one does learn a lot when trying to run Kubernetes in this environment using various hacks :)), my biggest challenge so far has been storage - I was very happy to see Azure Disk support being added to Kubernetes, but then I realized  I can't really use it.

**Comment by colemickens** [comment]
How are you achieving this? Are you doing vnet peering?

**Comment by FilipVozar** [comment]
I didn't know about VNET peering until just now, it's a relatively new feature and my cluster is older than that - thanks, I'll check it out.

In the past I've tried OpenVPN and VNET-to-VNET connection using VPN gateways, but I didn't like either of them (OpenVPN for administration overhead, VPN gateways mostly for their cost).

Now I'm assigning static public IPs to VMs and they use their public IPs to communicate to each other. This is a challenge, since VMs don't know about their public IPs, and I have to configure them manually or let VMs determine their own public IP (`curl ipecho.net/plain` :)).

One exception are master VMs - I'm running 3 smaller VMs in one subscription, these are K8S masters, they are on the same vnet and communicate with each other using their private vnet IPs.

PS: my cluster is actually Openshift Origin now (was plain K8S in the past), but same principles apply. It would be worth for me to switch back to K8S if I could have better integration with Azure using multiple subscriptions (storage, load balancer,...)

**Comment by colemickens** [comment]
This would be a rather nontrivial amount of work for a very uncommon
scenario. I don't foresee picking this up, personally.

Also, from the BizSpark FAQ, I don't think your usage pattern is
recommended or supported:

>Q: How do the monthly Azure credits for Visual Studio subscribers work?

>A: Azure credits are available through each of the five Visual Studio
Subscriptions available to your Startup through BizSpark. Each Visual
Studio subscription includes a US$150 monthly Azure credit while your
startup is active in the BizSpark program. More information about this
offer is available here. These credits are available to each subscriber
individually and cannot be pooled together.

**Comment by FilipVozar** [comment]
Okay, thank you for your response. Maybe I'll try to hack something together and publish it if it will be useful. My primary issue right now is storage, I think that provisioning a volume for a pod using Azure Blob Storage would require mapping pod's node to a subscription which this node belongs to, then creating and attaching VHD to this node using this subscription credentials. Then if pod is moved to another node, it would require that VHD is copied to a different storage account in a different subscription, based on the node that this pod was rescheduled to. As you said, nontrivial amount of work :)

I know our usage is not supported, but we are a small startup and we have our first prototype ready for testing just now, so we're trying to make the best use of what's available to us :) (we're dealing with data analysis, each VM counts)

**Comment by xied75** [comment]
@FilipVozar frankly you are picking a giant task which might not related to what your Startup should be spending time on. (Saying this also from a startup background). Azure Subscription owns Resource Group, Resource Group own your VM and everything. It is indeed very rare that people want to **pool** subs together, (and that's not what MS is happy for us to do anyway), when people have concerns, it's more on having cross data centre/region k8s, and that has business requirement to back it, i.e. DR/HA cases. 

If your first product is on data analysis I can understand you picked k8s as your infrastructure, of cause you'll code/test against your bizspark subs, but each deployment should not be long running, in this way you can keep your credits to the best usage, (I might say it's each Credit unit counts, not VM numbers).

I used to have two subs for testing one of my solution, I asked support to enable me to spin up 100 VMs at the same time, so that it can crunch lots of data and shutdown. You probably should ask for increasing the VM limits too.

I don't know what you use to deploy your infrastructure, (do you use Terraform etc.?) but I think the correct way should be having a set of files that can do the deployment and teardown very quickly, then you rotate your subs:

--> deploy to sub id 1: run, test, run, test, teardown
--> deploy to sub id 2: same as above
...
--> deploy to sub id 5: same

So then you round-robin your subs credit, and burn them evenly. Hope this could be a little help.

**Comment by FilipVozar** [comment]
@xied75 thank you for your input. We're not using much automation when deploying the infrastructure, right now we just spin up a VM and put it in Ansible inventory file. Most tools I've researched deal only with single Azure subscription.

Our service must be running constantly, as one of it's main business values is that it can notify our customers about something of their interest as close to real time as possible. The value of this information decreases with time. When our  API receives an item,  we'd like to process and analyze it within 1 minute (we could relax it to say, 10-15 minutes in the beginning until we get more money for better infrastructure, but still I'm not sure if that's worth the overhead of spinning up and shutting down VMs all the time).

What we are evaluating right now  are Azure Functions and other Azure services, instead of running our own infrastructure on top of Azure VMs. That means that we could use different subs for different services (one or two running Functions, some other running DocumentDB, etc...). The only thing we'd need to host are some stateless API services, which is easy and we only need low-tier VMs for running them. Our major issues with Azure Functions right now are low Python support and very slow filesystem (we spend 90%+ time just loading packages and modules from that slow filesystem, and this has to be done for every single item we process through our API - we're hoping that some batch support will be added for python Functions in the future).

**Comment by xied75** [comment]
@colemickens Given the conversation would you like to close this for now?

@FilipVozar So I suppose it's better to take this discussion offline, you can email me: xied75 at gmail.com, I'll see what I can do to help.

**Comment by colemickens** [comment]
@xied75 Yes, I do want to close this. Was going to let you two hash it out though. Of course there are other ways of collaborating and you've kindly shared your contact info.

Thanks to you both. Closing.

**Comment by lmcarreiro** [comment]
Anyone know if today it`s possible to add VMs from multiple azure subscriptions as new nodes into the same kubernetes cluster?

I think that at the time this issue was created, this [Virtual Networking Peering](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview) didn`t exist yet.
