### ISSUE TITLE
RUNTIME ERROR: Field does not exist: weave_net

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubernetes-anywhere#371]
weave-net Addon is optional. but selecting N results in to error.
```
*
* Phase 3: Deploying Addons
*
Run the addon manager? (phase3.run_addons) [Y/n/?] (NEW) Y
  Run kube-proxy? (phase3.kube_proxy) [Y/n/?] (NEW) Y
  Run the dashboard? (phase3.dashboard) [Y/n/?] (NEW) Y
  Run heapster? (phase3.heapster) [Y/n/?] (NEW) Y
  Run kube-dns? (phase3.kube_dns) [Y/n/?] (NEW) Y
  Run weave-net? (phase3.weave_net) [N/y/?] (NEW) N
#
# configuration written to .config
#
make[1]: Leaving directory '/opt/kubernetes-anywhere'
util/config_to_json .config > .config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do deploy-cluster )
RUNTIME ERROR: Field does not exist: weave_net
	../../phase3/all.jsonnet:2:42-58	function <if_enabled>
	../../phase3/all.jsonnet:10:16-83	thunk <array_element>
	std.jsonnet:631:46-53	thunk <b>
	../../phase3/all.jsonnet:3:50	function <func>
	std.jsonnet:631:32-54	thunk <running>
	std.jsonnet:631:17-64	function <aux>
	std.jsonnet:631:17-64	function <aux>
	std.jsonnet:632:9-31	function <anonymous>
	../../phase3/all.jsonnet:3:21-60	function <join>
	../../phase3/all.jsonnet:(5:14)-(11:15)	thunk <manifest>
	...
	vSphere.jsonnet:132:21-133	thunk <array_element>
	vSphere.jsonnet:(130:27)-(135:19)	object <anonymous>
	vSphere.jsonnet:(129:32)-(136:17)	object <anonymous>
	vSphere.jsonnet:(128:27)-(137:12)	thunk <array_element>
	vSphere.jsonnet:(128:26)-(141:13)	object <anonymous>
	vSphere.jsonnet:(121:17)-(142:9)	object <anonymous>
	std.jsonnet:(943:13)-(952:13)	object <anonymous>
	std.jsonnet:(943:13)-(952:13)	object <anonymous>
	all.jsonnet:3:49-79	object <anonymous>
	During manifestation	
Makefile:63: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:41: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2
```

@abrarshivani @BaluDontu @tusharnt

**Comment by divyenpatel** [comment]
@pipejakob  can you take a look?

**Comment by pipejakob** [comment]
Ah, I encountered this myself during development and meant to open a proper issue for it. I don't think this is unique to weave-net, but any addon you disable. The root cause is that `make config` or `make menuconfig` will omit the config entry if you answer `n` for these addon options, even adding a commented-out line about the answer being `n`, but the rest of our addon jsonnet files assume that there will be config entries for them, set to `n`.

The really quick fix is to manually edit `.config` and add the line:

    .phase3.weave_net=n

I'd like to make kubernetes-anywhere tolerant of these lines being missing entirely (instead of just set to `n`), but hopefully the above will unblock you, and I'll file an issue for this to work out of the box.

**Comment by pipejakob** [comment]
I've opened a PR for a better fix: https://github.com/kubernetes/kubernetes-anywhere/pull/372

**Comment by pipejakob** [comment]
@divyenpatel It looks like you verified that the PR fixed things for you (and it's merged now). Is there more for this issue, or do you want to close it?

**Comment by divyenpatel** [comment]
Thanks @pipejakob for quick fix.
Closing this issue.
