### ISSUE TITLE
Validation: Expected 5 healthy nodes; found 0. (660s elapsed)

### ISSUE THREAD

**Issue by psyolent** [kubernetes/kubernetes-anywhere#424]
hey

so getting thru deploying this in a secured work environment with VCSA 6.5.1, and vSphere in 5.5u3, using vDS in this particular instance. 

i get the cluster and nodes deployed but get to a point where it goes to discover nodes and master ; and ; never finds a thing, not a master, not a node, zilcho, all i get is an infinite supply of Validation: Expected 5 healthy nodes; found 0. (xxxxxxxs elapsed)

what action is occuring when its doing this and can i manually try to invoke it?

thanks heaps

**Comment by psyolent** [comment]
note, i can get on the master, and, ping everything just fine - no issues - via normal net OR via flannel - so i know connectivity is there and a happening thing. 

of note i can deploy the same in my lab in the exact same way with no issue whatsoever.

**Comment by divyenpatel** [comment]
@psyolent we can help.
Can you login to the master node and see api server is running?

```
root@master [ ~ ]# docker ps | grep "hyperkube apiserver"
601f654723ce        3b32bac67a2f                                   "/hyperkube apiserver"   12 hours ago        Up 12 hours                             k8s_kube-apiserver_kube-apiserver-master_kube-system_c59930d330f33cbcff09be57d5ec067a_1
root@master [ ~ ]#
```

Can you grab API server logs and attach to this issue?

Log location should be
`cd /var/lib/docker/containers/601f654723ce*`
here 601f654723ce is the container id of API server.

One more thing to check is kubeconfig.json file in your kubernetes-anywhere container.

Can you ping the Server IP address mentioned in the /opt/kubernetes-anywhere/phase1/vsphere/.tmp/kubeconfig.json from your container?


@BaluDontu @tusharnt @rohitjogvmw @luomiao

**Comment by psyolent** [comment]
hey, very appreciated.
no its not running on the master mate.  ; ie: the PS just returns empty - so that could be something of a problem :)

now for the logs. 
in the log location ie: /var/lib/docker/containers/ , theres a mass of directories for different things. 
the log file in each of them ends with {"log":"Error: failed to run Kubelet: could not init cloud provider \"vsphere\": 2:25: unknown escape sequence\n","stream":"stderr","time":"2017-08-12T04:01:16:186486095Z"}
they are all the same

yes, the refer in the kubeconfig to that IP pings just fine

**Comment by divyenpatel** [comment]
@psyolent  
Problem could be in the vsphere.conf file. Look at  `/etc/kubernetes/vsphere.conf`
We need to escape special characters in vsphere.conf file.

Recently @jck-ccl has fixed the issue - https://github.com/kubernetes/kubernetes-anywhere/pull/416

If you are using `cnastorage/kubernetes-anywhere:latest` image to deploy kubernetes cluster then we need to include this change in the image.

Meanwhile you can try deploying cluster using `cnastorage/kubernetes-anywhere:vmc` image.

```
docker pull cnastorage/kubernetes-anywhere:vmc
docker run -it --rm --env="PS1=[container]:\w> " --net=host cnastorage/kubernetes-anywhere:vmc /bin/bash
```

Let us know if the issue persist with this new image as well.

**Comment by psyolent** [comment]
excellent. that build went thru successfully. thanks divyen! 
now to deal with this 'unauthorized' issue when i go to the Kubernetes Master.

cheers, Greg

**Comment by divyenpatel** [comment]
@psyolent you can close this issue and open a new issue for 'unauthorized' error on the master node with more detail.

**Comment by edqallen** [comment]
Any movement on getting this into master yet?  Having the same problem here with vCenter 6 managing a vSphere 6 cluster with both a vDS and a SDRS storage datastore, though it results in it getting stuck repeating "found 1" instead of "found 0".  With the vma labeled pull from github It starts off looking like this

```
vsphere_virtual_machine.kubevm5: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm3: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm4: Still creating... (1m0s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m0s elapsed)
```

Eventually *one* of them finishes and the deploy continues while messages like this begin to appear periodically:

```
null_resource.node5: Still creating... (50s elapsed)
null_resource.node3: Still creating... (50s elapsed)
null_resource.node2: Still creating... (50s elapsed)
null_resource.master: Still creating... (50s elapsed)
```

Eventually we get here:

```
null_resource.master: Creation complete (ID: 5143754012539180185)
null_resource.node2: Still creating... (1m20s elapsed)
null_resource.node4: Still creating... (1m20s elapsed)
null_resource.node5: Still creating... (1m20s elapsed)
null_resource.node3: Still creating... (1m20s elapsed)
null_resource.node3: Still creating... (1m30s elapsed)
null_resource.node2: Still creating... (1m30s elapsed)
null_resource.node4: Still creating... (1m30s elapsed)
null_resource.node5: Still creating... (1m30s elapsed)
null_resource.node5: Creation complete (ID: 3344147625474641584)
null_resource.node4: Creation complete (ID: 8249285824638980609)
null_resource.node3: Creation complete (ID: 6641015770368322059)
null_resource.node2: Creation complete (ID: 3161490179035910706)

Apply complete! Resources: 22 added, 0 changed, 0 destroyed.
```

Which results in the final result...

```
Validation: Expected 5 healthy nodes; found 1. (10s elapsed)
Validation: Expected 5 healthy nodes; found 1. (20s elapsed)
Validation: Expected 5 healthy nodes; found 1. (30s elapsed)
Validation: Expected 5 healthy nodes; found 1. (40s elapsed)
Validation: Expected 5 healthy nodes; found 1. (50s elapsed)
Validation: Expected 5 healthy nodes; found 1. (60s elapsed)
Validation: Expected 5 healthy nodes; found 1. (70s elapsed)
Validation: Expected 5 healthy nodes; found 1. (80s elapsed)
Validation: Expected 5 healthy nodes; found 1. (90s elapsed)
Validation: Expected 5 healthy nodes; found 1. (100s elapsed)
Validation: Expected 5 healthy nodes; found 1. (110s elapsed)
Validation: Expected 5 healthy nodes; found 1. (120s elapsed)
Validation: Expected 5 healthy nodes; found 1. (130s elapsed)
Validation: Expected 5 healthy nodes; found 1. (140s elapsed)
```

Which lasts indefinitely.

**Comment by edqallen** [comment]
An update to my previous post:

This issue, for me at least, appears to be due to choosing too small of a management network size for the cluster.  This is my first time messing with Kubernetes, I am attempting to create a cluster to migrate machines to from our existing Rancher cluster in prep for the release of Rancher 2.0.  I did not realize that Kubernetes requires a /24 **for each node**, so I had just allocated a single /24 to the whole cluster when prompted during make config.

I was reading about the networking in prep for trying a manual install since this hasn't been working when I stumbled across that requirement.

It should probably be mentioned during the config process, or better yet, an error displayed if you choose a network size too small for the number of nodes you've selected.

**Comment by abrarshivani** [comment]
@edqallen Thanks for trying out this stuff will add a help message to config process

**Comment by D3nn** [comment]
I am also having an issue deploying to my vsphere cluster but the issue seems to be coming from a different source, on startup of the kubelet container, I get the error:

```Dec 13 09:43:27 kubernetes-master docker[826]: Error: unknown flag: --api-servers```

vsphere environment (managed via vcenter)
Server vsphere 6.0.0 (machine image 10)
Client vsphere 6.0.0

Kubernetes version attempted to deploy: v1.8.5
OVA: [OVA For vSphere 5.5 with Virtual Machine Hardware Version 10](https://storage.googleapis.com/kubernetes-anywhere-for-vsphere-cna-storage/KubernetesAnywhereTemplatePhotonOSESX5.5.ova)  (tried vSphere 6.0+ OVA but cluster refused to deploy it)
Ignite: docker.io/cnastorage/k8s-ignition:v2
docker_registry: docker.io/googlecontainer

Anything I'm missing?

**Comment by divyenpatel** [comment]
@D3nn For 1.8 kubernetes releases you can use this new ignition image `cnastorage/k8s-ignition:v1.8-dev-release` This ignition image uses new kubelet flags for 1.8 releases.
