### ISSUE TITLE
kubernetes kubeadm-gce-* tests failing due to missing node configuration

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes-anywhere#561]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-cni-flannel/3436

None of the nodes start because:
`Sep  6 15:44:40 e2e-3436-098af-node-f2tq kubelet[5051]: F0906 15:44:40.442940    5051 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory`

And that may be due to failures in the kubernetes-anywhere Makefile?
```
W0906 15:41:11.941] 2018/09/06 15:41:11 process.go:153: Running: make -C /workspace/k8s.io/kubernetes-anywhere kubeconfig-path
I0906 15:41:12.041] make: Entering directory '/workspace/k8s.io/kubernetes-anywhere'
I0906 15:41:12.042] util/config_to_json /workspace/k8s.io/kubernetes-anywhere/.config > /workspace/k8s.io/kubernetes-anywhere/.config.json
I0906 15:41:12.063] Makefile:57: recipe for target 'kubeconfig-path' failed
I0906 15:41:12.063] make: Leaving directory '/workspace/k8s.io/kubernetes-anywhere'
I0906 15:41:12.064] make: Entering directory '/workspace/k8s.io/kubernetes-anywhere'
I0906 15:41:12.071] make do WHAT=deploy-cluster
I0906 15:41:12.076] make[1]: Entering directory '/workspace/k8s.io/kubernetes-anywhere'
I0906 15:41:12.085] ( cd "phase1/gce"; ./do deploy-cluster )
W0906 15:41:12.186] Cannot find kubeconfig file. Have you started a cluster with "make deploy" yet?
W0906 15:41:12.186] make: *** [kubeconfig-path] Error 1
W0906 15:41:12.186] 2018/09/06 15:41:12 process.go:155: Step 'make -C /workspace/k8s.io/kubernetes-anywhere kubeconfig-path' finished in 122.252521ms
```

**Comment by neolit123** [comment]
@dcbw 
i've been investigating the same failures except in:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-12/3
and the rest of the red k-a tests.

i don't think this is a critical problem:
```
Cannot find kubeconfig file. Have you started a cluster with "make deploy" yet?
W0906 15:41:12.186] make: *** [kubeconfig-path] Error 1
```

this is a bit of misconfiguration between the the test-infra `anywhere` deployment and k-a itself.
the first verification fails bacause `make deploy` was not called yet.
you can find the same error on green tests.

also a false positive:
```
failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
```

this is just an error because the file doesn't exist yet and kubeadm hasn't written it.
works fine for 1.11 and older k8s versions as can be seen here:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-1.11

i'm looking at something else which happens for all k-a 1.12 tests:
```
E0906 15:44:38.798398    6289 reflector.go:134] k8s.io/csi-api/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.CSIDriver: csidrivers.csi.storage.k8s.io is forbidden: User "system:node:e2e-3436-098af-master" cannot list resource "csidrivers" in API group "csi.storage.k8s.io" at the cluster scope
```

i wonder if this is something about the old version (1.12) docker-engine that k-a uses or something about 
k8s CSI bugs vs GCE.

@kubernetes/sig-cluster-lifecycle

**Comment by neolit123** [comment]
this is unrelated as well:
```
E0906 15:44:38.798398    6289 reflector.go:134] k8s.io/csi-api/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.CSIDriver: csidrivers.csi.storage.k8s.io is forbidden: User "system:node:e2e-3436-098af-master" cannot list resource "csidrivers" in API group "csi.storage.k8s.io" at the cluster scope
```
a just reported it to sig-storage and a separate issue was filed.

**Comment by neolit123** [comment]
let's track this in a single location:
https://github.com/kubernetes/kubernetes/issues/68475

/close
